data:
  data_path: "dataset/ultragood_v5/"

training:
  batch_size: 36
  num_workers: 5
  learning_rate: 0.0004
  max_epochs: 100
  weight_decay: 0.0001
  seed: 42

scheduler:
  type: "none"
  T_max: 10
  min_lr: 0.001
  warmup_epochs: 5